### ISSUE TITLE
no initThemeProvider on import

### ISSUE THREAD

**Issue by psudocode** [CptFabulouso/react-native-theme-provider#1]
hi [CptFabulouso](https://github.com/CptFabulouso),

I use your module with ts, but I can't import `initThemeProvider` from `@pavelgric/react-native-theme-provider`.

Btw you make great documentation, and it makes this module awesome.

Thank you

**Comment by CptFabulouso** [comment]
Hi, thank you :) And I am sorry, I did not realize someone else might be using this library and I made changes directly to master, which are not ready to be released to npm yet.
I won't do that anymyore, but meanwhile please refer to these docs  https://github.com/CptFabulouso/react-native-theme-provider/tree/0.0.7

**Comment by psudocode** [comment]
Thank you, CptFabulouso.

**Comment by CptFabulouso** [comment]
Hi @psudocode 

With version 0.1.1 you can now use the `initThemeProvider` and follow the docs on master.
